### PR TITLE
Update aou config JSON path

### PR DESCRIPTION
**Pull request by calbach**
To match https://github.com/all-of-us/workbench/pull/598

### CODE REVIEW

**Comment by calbach** [comment]
@danqrodney also I need access to this repo

**Comment by danqrodney** [comment]
@calbach I invited you to be a collaborator on this repo... you should have received an email about it I think?

**Comment by danqrodney** [comment]
Note: after you merge this you'll need to tag pyclient and update:

https://github.com/all-of-us/workbench/blob/master/api/scripts/setup_notebook_cluster.sh

 to refer to the new tag.

**Comment by calbach** [comment]
Oops thanks, forgot I'd asked for this one. Invites go to my personal inbox so of course I missed it. Will try and test this out when I'm able, but Leo it seems has an SSL issue again.

**Comment by calbach** [comment]
I had a pretty rough manual testing experience here. Trying to improve that a bit:

- Added manual testing docs
- Support installing from an arbitrary GitHub branch, which would greatly simplify the above manual testing process: https://github.com/DataBiosphere/leonardo/pull/266
- Better debugging of the user script: https://github.com/DataBiosphere/leonardo/issues/265

I also realized that this client lib doesn't work in Python2.7, though you may have already mentioned that. Once I got the pip install working, there seemed to be some import errors within the package; fixed those in this PR too.

Finally, confirmed the config file reading actually does work.

**Pull request merged**
